server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8080
              predicates:
                - Path=/api/v1/users/**
            - id: product-service
              uri: http://product-service:8080
              predicates:
                - Path=/api/v1/products/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
